rackerlabs/python-lavaclient

lavaclient/api/clusters.py
Allow `node_groups` to be either a `list` of `dicts`, or a single, nested `dict` with the node group ID's as keys.
=> Allow node_groups to be a nested dict

README.md, docs/client.rst, docs/index.rst, docs/intro.rst, lavaclient/__init__.py, lavaclient/api/stacks.py, lavaclient/client.py, tests/cli/test_stacks_cli.py, tests/test_stacks.py
Add more introductory documentation.
=> Flesh out introductory docs

docs/api/credentials.rst, lavaclient/api/credentials.py, lavaclient/api/response.py
Add more credentials documentation and examples.
=> Add more credentials documentation

docs/api/flavors.rst, lavaclient/api/response.py
Add more flavors documentation and examples.
=> Add flavors documentation

docs/api/nodes.rst, lavaclient/api/nodes.py, lavaclient/api/response.py
Add nodes documentation and examples.
=> Add nodes documentation

docs/api/scripts.rst
Add scripts documentation and examples.
=> Add scripts documentation

docs/api/stacks.rst, lavaclient/api/response.py, lavaclient/api/stacks.py, tests/cli/test_stacks_cli.py, tests/test_stacks.py
Add stacks documentation.  Also commented out methods that return a HTTP 405 error, i.e. `create` and `delete`.
=> Add stacks documentation

lavaclient/cli.py
Change Tenand ID to Tenant ID in help response
=> Fix typo in help command

lavaclient/api/clusters.py, lavaclient/util.py, tests/cli/test_clusters_cli.py
Add method to create SSH tunnels, e.g. `lava clusters ssh_tunnel <id> <local port> <remote port> --component HiveServer2`
=> Add ssh_tunnel method

lavaclient/api/clusters.py, lavaclient/api/credentials.py, lavaclient/api/scripts.py, tests/cli/test_clusters_cli.py, tests/cli/test_credentials_cli.py, tests/cli/test_scripts_cli.py
All confirmation dialogs for delete commands in CLI, e.g. `clusters delete`
=> Add delete confirmations

lavaclient/client.py, lavaclient/constants.py, test-requirements.txt, tests/conftest.py, tests/test_auth.py, tests/test_client.py, tests/test_versions.py
Once identity enables v2 version, use this endpoint.
CBD-4079 #fixes
=> V2 identity endpoint support.

CHANGELOG.md, docs/api/credentials.rst, lavaclient/_version.py, lavaclient/api/clusters.py, lavaclient/api/credentials.py, lavaclient/api/response.py, lavaclient/util.py, tests/cli/test_credentials_cli.py, tests/conftest.py, tests/test_clusters.py
Enable ambari credential management methods.
=> Enable ambari credential management

CHANGELOG.md, lavaclient/api/response.py, lavaclient/api/stacks.py, tests/cli/test_stacks_cli.py, tests/test_stacks.py
Re-enable stack creation and delete, as well as tests.
=> Re-enable stacks create/delete

lavaclient/api/credentials.py, tests/cli/test_credentials_cli.py
Kind of sucks if you have to put your password in plaintext on the command line.
=> Use getpass to grab ambari password

CHANGELOG.md, lavaclient/_version.py, lavaclient/api/response.py, lavaclient/api/stacks.py, test-requirements.txt, tests/cli/test_stacks_cli.py
Improve appearance of `stacks` commands, especially `stacks list`.
=> Improve output from `stacks` commands

lavaclient/util.py
Display table on list should happen on every item instead of list itself.
=> Fix display table.

docs/access.rst, docs/index.rst
Is this explanatory enough?  Anything I missed?
=> Add a tutorial for ssh and socks proxy usage

docs/api/credentials.rst, requirements.txt, setup.py
Minor documentation update on credentials.
=> Clarify current status of credential updates

CHANGELOG.md, lavaclient/_version.py, lavaclient/api/response.py, tests/cli/test_clusters_cli.py, tests/cli/test_credentials_cli.py
Show cluster credentials in CLI output
=> Show cluster credentials in clusters response

CHANGELOG.md, lavaclient/_version.py, release.sh, setup.cfg
Create separate wheels for python 2 and 3
=> Fix wheel packaging issue

release.sh
I keep forgetting to create tags, so this should handle it automatically.
=> Automatically tag releases

CHANGELOG.md, docs/api/scripts.rst, lavaclient/_version.py, lavaclient/api/response.py, tests/cli/test_clusters_cli.py, tests/conftest.py
Show user script status for each cluster node.
=> Support node scripts

CHANGELOG.md, lavaclient/_version.py, lavaclient/api/clusters.py, tests/test_clusters.py
=> Validate cluster username
