lavaclient/api/clusters.py, lavaclient/api/resource.py, lavaclient/cli.py, lavaclient/client.py, lavaclient/util.py, tests/cli/conftest.py, tests/cli/test_clusters_cli.py
In the CLI, if we try to automatically upload the user's ssh keypair, but the keypair doesn't exist, catch the ensuing `IOError` and give the user instruction.
=> Add CLI check for missing SSH key

docs/api/limits.rst, lavaclient/api/limits.py, lavaclient/api/response.py, tests/test_limits.py
Originally, `client.limits.get` forced you to access the `absolute` attribute before getting any useful information.  Now that method returns the content of the `absolute` attribute instead of the wrapped response.
=> Add limits docs; fix limits response object

CHANGELOG.md, lavaclient/api/clusters.py
Turns out there's another message that's returned when the request ssh key isn't available.
=> Fix credentials issue in CLI cluster create

CHANGELOG.md, requirements.txt
Upgrade `python_keystoneclient` and `oslo.i18n` dependencies to fix library conflict issue.
=> Upgrade keystone/oslo deps

lavaclient/api/response.py, lavaclient/keystone.py
On cluster create, display credentials for any service users.  Note that these will not be returned by any other cluster method, e.g. `get`
=> Display service user creds on cluster create

lavaclient/api/clusters.py, lavaclient/api/nodes.py, lavaclient/api/response.py, tests/cli/test_clusters_cli.py, tests/cli/test_nodes_cli.py, tests/conftest.py
Instead of displaying components alongside the nodes (which is really ugly and cluttered), display components information *after* the nodes in a separate table.
```
+-----------------------------------------------------------------------------------------------------------+
|                                                   Nodes                                                   |
+--------------------------------------+-------------+-----------+--------+----------------+----------------+
|                  ID                  |     Name    |    Role   | Status |   Public IP    |   Private IP   |
+--------------------------------------+-------------+-----------+--------+----------------+----------------+
| 456e09ef-5c7a-42e7-9342-2a27bdf91c44 |   master-1  |   master  | ACTIVE | …
```
=> Improve nodes list display

docs/api/credentials.rst, lavaclient/api/clusters.py, lavaclient/api/credentials.py, lavaclient/api/response.py, lavaclient/util.py, tests/cli/test_credentials_cli.py, tests/conftest.py, tests/test_clusters.py
Several changes to reflect recent credentials handling changes in the API:
- In `clusters.create`, `connectors` are deprecated in favor of `credentials`
- Added Ambari credentials management
=> Add ambari credential methods

lavaclient/cli.py, tests/cli/test_clusters_cli.py, tests/cli/test_nodes_cli.py, tests/conftest.py
Sometimes, you want to be able to pipe the output of the `lava` script to other commands, e.g. `awk`.  Previously, we always printed a formatted table, complete with borders, which would not be terribly useful when piped elsewhere.  Here, I introduce functionality to fix that issue.
When the `lava` script detects that it is piping to another command (via `sys.stdout.isatty()`), it automatically disables pretty-printing, instead opting to print a simple delimited table.  This behavior can be controlled using the `--format` and `--no-format` options; this can be helpful if you want to pipe the formatted table to another command instead, e.g. using `tee` to log the output to a file.
In addition, I've changed the `--debug` (`-d`) option to allow multiple uses, which enables higher debugging …
=> Add CLI options to print unformatted tables

CHANGELOG.md, lavaclient/_version.py, lavaclient/api/clusters.py
Since the Ambari node doesn't allow SSH access, remove it from the list of nodes that can be SSH'ed to.
=> Remove ambari node from ssh-able nodes list

CHANGELOG.md, lavaclient/api/clusters.py, lavaclient/api/credentials.py, lavaclient/api/scripts.py
Add `--force` option to CLI delete methods so that you can skip the confirmation dialog.
=> Add --force to delete methods

lavaclient/cli.py, lavaclient/client.py, lavaclient/constants.py, lavaclient/error.py, tests/test_client.py
I wasn't able to properly mock the guts of urllib3 in such
a way as to create unit tests for the retries, but I did
manual testing and it worked as expected.
=> Add automatic retries on network errors and 503 responses

CHANGELOG.md, docs/api/clusters.rst, lavaclient/_version.py, lavaclient/api/clusters.py, lavaclient/cli.py, release.sh, tests/cli/test_clusters_cli.py
Allow SSH to impaired clusters.  Also do some housekeeping, e.g. creating release script, adding some missing docs, and fixing the `--version` flag.
=> Allow SSH to IMPAIRED clusters

CHANGELOG.md, lavaclient/api/response.py, tests/cli/conftest.py, tests/cli/test_clusters_cli.py, tests/cli/test_credentials_cli.py, tests/cli/test_limits_cli.py, tests/cli/test_nodes_cli.py, tests/cli/test_stacks_cli.py, tests/cli/test_workloads_cli.py
Instead of showing a series of `{name='component'}`, just show the component names
=> Show node component names instead of json

lavaclient/util.py, tests/test_util.py
I plan to use this in the admin client, but putting it
here with the related methods so it's available for both.
=> Add print_dict_table for table-ifying arbitrary dicts

CHANGELOG.md, lavaclient/_version.py, lavaclient/cli.py, tests/cli/test_cli.py
Fix the unformatted (i.e. `--no-format`) output for single-item methods, e.g. `clusters get`.
=> Fix unformatted output for single items

CHANGELOG.md, lavaclient/api/resource.py, lavaclient/cli.py, tests/cli/test_cli.py
I wasn't setting the `_command_line` attribute in `Resource` objects properly, so CLI-specific output was still being printed while in the `shell` command for certain methods, the most notable of which was the `clusters.wait` method.
=> Don't show cli-specific output in shell

.travis.yml, CHANGELOG.md, lavaclient/_version.py, lavaclient/api/clusters.py, requirements.txt, setup.py, tests/cli/test_clusters_cli.py
You can now start/stop/restart services on a cluster, so long as they're running Ambari (which is pretty much everything).
=> Add service management methods

CHANGELOG.md, lavaclient/api/clusters.py, lavaclient/api/credentials.py, lavaclient/api/scripts.py, lavaclient/api/stacks.py
Add support for deleting multiple items at once to the following CLI commands:
- `lava clusters delete`
- `lava credentials delete_ssh_key`
- `lava credentials delete_cloud_files`
- `lava credentials delete_s3`
- `lava credentials delete_ambari`
- `lava scripts delete`
- `lava stacks delete`
=> Support deleting multiple items at once

release.sh, setup.cfg
Re-enable universal (python 2/3) wheel packages, since we no longer have version-dependent dependencies.
=> Re-enable universal wheel packages

CHANGELOG.md, lavaclient/_version.py, lavaclient/api/clusters.py, tests/cli/test_clusters_cli.py
The API is more lenient on node group ID's than the client allows.  This lets the CLI accept any node group ID that does not contain parentheses.
Note that the API also allows for parentheses, but come on.
=> Make node group ID regex more lenient

CHANGELOG.md, lavaclient/api/nodes.py, tests/cli/test_nodes_cli.py, tests/conftest.py, tests/test_nodes.py
Ability to delete a single node from a cluster.
Dependent on https://github.rackspace.com/CloudBigData/lava/pull/2197
=> Add delete a node

CHANGELOG.md, lavaclient/__init__.py, lavaclient/api/clusters.py, lavaclient/api/nodes.py, lavaclient/error.py, tests/cli/test_clusters_cli.py
Allow cluster actions to work using either the cluster ID or name, e.g.
```bash
$ lava clusters get <cluster ID>
```
or...
```bash
$ lava clusters get <cluster name>
```
=> Allow cluster actions to work with cluster ID or name
